name: Jekyll site CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Add masks
        run: |
          echo "::add-mask::${{ secrets.ENDPOINT_IP }}"
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: ${{ secrets.CONFIG }}
          if_key_exists: replace
      - name: Setup rclone
        run: |
          sudo apt-get install -y rclone
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      #    - name: install ImageMagick
      #      run: |
      #        sudo apt install -y imagemagick
      #    - name: Cache dependencies
      #      id: cache-deps
      #      uses: actions/cache@v1
      #      with:
      #        path: vendor/cache
      #        key: bundle-use-ubuntu-latest-jekyll-${{ hashFiles('**/Gemfile.lock') }}
      #        restore-keys: |
      #          bundle-use-ubuntu-latest-jekyll-
      #    - name: Install dependencies
      #      run: |
      #        bundle install
      #        bundle package
      - name: Build site
        run: .github/scripts/build.sh "${{ secrets.NOT_IN_REPO }}"
      - name: Deploy
        run: .github/scripts/deploy.sh "${{ secrets.BUNNY_API_KEY }}"
